# for local development only
services:
  postgres_user_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_user_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_USER_SERVICE:-fpuser_user_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_USER_SERVICE:-fppass_user_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_USER_SERVICE:-fpdb_user_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_user_service_network

  postgres_billing_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_billing_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_BILLING_SERVICE:-fpuser_billing_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_BILLING_SERVICE:-fppass_billing_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_BILLING_SERVICE:-fpdb_billing_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_billing_service_network

  postgres_order_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_order_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_ORDER_SERVICE:-fpuser_order_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_ORDER_SERVICE:-fppass_order_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_ORDER_SERVICE:-fpdb_order_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_order_service_network

  postgres_notification_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_notification_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_NOTIFICATION_SERVICE:-fpuser_notification_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_NOTIFICATION_SERVICE:-fppass_notification_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_NOTIFICATION_SERVICE:-fpdb_notification_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_notification_service_network

  postgres_warehouse_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_warehouse_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_WAREHOUSE_SERVICE:-fpuser_warehouse_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_WAREHOUSE_SERVICE:-fppass_warehouse_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_WAREHOUSE_SERVICE:-fpdb_warehouse_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_warehouse_service_network

  postgres_delivery_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_delivery_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_DELIVERY_SERVICE:-fpuser_delivery_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_DELIVERY_SERVICE:-fppass_delivery_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_DELIVERY_SERVICE:-fpdb_delivery_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_delivery_service_network

  postgres_auth_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5438:5432"
    volumes:
      - postgres_data_auth_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_AUTH_SERVICE:-fpuser_auth_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_AUTH_SERVICE:-fppass_auth_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_AUTH_SERVICE:-auth_db}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - fp_auth_service_network

  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VIRTUAL_HOST:-/}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - rabbitmq_network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    user: "10001:10001"
    ports:
      - "4318:4318"
      - "4317:4317"
      - "3200:3200"
    command:
      - --config.file=/etc/tempo-config.yml
    volumes:
      - ./tempo-config.yml:/etc/tempo-config.yml:ro
      - tempo_data:/var/tempo
    healthcheck:
      test:
        [ "CMD-SHELL", "curl -f http://localhost:3200/status || exit 1" ]
      interval: 15s
      timeout: 10s
      start_period: 60s
      retries: 8
    networks:
      - fp_monitoring_network

volumes:
  postgres_data_user_service:
  postgres_data_billing_service:
  postgres_data_order_service:
  postgres_data_notification_service:
  postgres_data_warehouse_service:
  postgres_data_delivery_service:
  postgres_data_auth_service:
  rabbitmq_data:
  tempo_data:

networks:
  fp_user_service_network:
    name: fp_user_service_network
    driver: bridge
  fp_billing_service_network:
    name: fp_billing_service_network
    driver: bridge
  fp_order_service_network:
    name: fp_order_service_network
    driver: bridge
  fp_notification_service_network:
    name: fp_notification_service_network
    driver: bridge
  fp_warehouse_service_network:
    name: fp_warehouse_service_network
    driver: bridge
  fp_delivery_service_network:
    name: fp_delivery_service_network
    driver: bridge
  fp_auth_service_network:
    name: fp_auth_service_network
    driver: bridge
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
  fp_monitoring_network:
    name: fp_monitoring_network
    driver: bridge
