server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"
        grpc:
          endpoint: "0.0.0.0:4317"

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

overrides:
  defaults:
    compaction:
      block_retention: 24h

backend_worker:
  compaction:
    block_retention: 24h
    compaction_window: 1h
    max_block_bytes: 107374182400
    max_time_per_tenant: 5m
    compaction_cycle: 30s

