{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fpchart.fullname" . }}-health-ingress
  labels:
    {{ include "fpchart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /actuator/health
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /health/user
            pathType: Exact
            backend:
              service:
                name: {{ include "fpchart.fullname" . }}-user-service
                port:
                  number: {{ (index .Values.services "user-service").port }}
          - path: /health/billing
            pathType: Exact
            backend:
              service:
                name: {{ include "fpchart.fullname" . }}-billing-service
                port:
                  number: {{ (index .Values.services "billing-service").port }}
          - path: /health/order
            pathType: Exact
            backend:
              service:
                name: {{ include "fpchart.fullname" . }}-order-service
                port:
                  number: {{ (index .Values.services "order-service").port }}
          - path: /health/notification
            pathType: Exact
            backend:
              service:
                name: {{ include "fpchart.fullname" . }}-notification-service
                port:
                  number: {{ (index .Values.services "notification-service").port }}
          - path: /health/warehouse
            pathType: Exact
            backend:
              service:
                name: {{ include "fpchart.fullname" . }}-warehouse-service
                port:
                  number: {{ (index .Values.services "warehouse-service").port }}
          - path: /health/delivery
            pathType: Exact
            backend:
              service:
                name: {{ include "fpchart.fullname" . }}-delivery-service
                port:
                  number: {{ (index .Values.services "delivery-service").port }}
{{- end }}
