CREATE TABLE IF NOT EXISTS auth_outbox
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL,
    created          TIMESTAMP                               NOT NULL,
    updated          TIMESTAMP                               NOT NULL,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    event_id         VARCHAR(36)                             NOT NULL,
    payload          TEXT                                    NOT NULL,
    status           VARCHAR(10)                             NOT NULL CHECK (status IN ('NEW', 'SENT', 'FAILED')),
    attempts         INT                                     NOT NULL DEFAULT 0,
    sent_at          TIMESTAMP,

    CONSTRAINT pk_auth_outbox PRIMARY KEY (id),
    CONSTRAINT uq_auth_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_outbox_status ON auth_outbox (status);
