# for local development only
services:
  postgres_user_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_user_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_USER_SERVICE:-hw09user_user_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_USER_SERVICE:-hw09pass_user_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_USER_SERVICE:-hw09db_user_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - hw09_user_service_network

  postgres_billing_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_billing_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_BILLING_SERVICE:-hw09user_billing_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_BILLING_SERVICE:-hw09pass_billing_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_BILLING_SERVICE:-hw09db_billing_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - hw09_billing_service_network

  postgres_order_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_order_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_ORDER_SERVICE:-hw09user_order_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_ORDER_SERVICE:-hw09pass_order_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_ORDER_SERVICE:-hw09db_order_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - hw09_order_service_network

  postgres_notification_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_notification_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_NOTIFICATION_SERVICE:-hw09user_notification_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_NOTIFICATION_SERVICE:-hw09pass_notification_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_NOTIFICATION_SERVICE:-hw09db_notification_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - hw09_notification_service_network

  postgres_warehouse_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_warehouse_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_WAREHOUSE_SERVICE:-hw09user_warehouse_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_WAREHOUSE_SERVICE:-hw09pass_warehouse_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_WAREHOUSE_SERVICE:-hw09db_warehouse_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - hw09_warehouse_service_network

  postgres_delivery_service:
    image: postgres:16.11
    restart: always
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_delivery_service:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME_DELIVERY_SERVICE:-hw09user_delivery_service}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_DELIVERY_SERVICE:-hw09pass_delivery_service}
      POSTGRES_DB: ${SPRING_DATASOURCE_DBNAME_DELIVERY_SERVICE:-hw09db_delivery_service}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - hw09_delivery_service_network

  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VIRTUAL_HOST:-/}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - rabbitmq_network

volumes:
  postgres_data_user_service:
  postgres_data_billing_service:
  postgres_data_order_service:
  postgres_data_notification_service:
  postgres_data_warehouse_service:
  postgres_data_delivery_service:
  rabbitmq_data:

networks:
  hw09_user_service_network:
    name: hw09_user_service_network
    driver: bridge
  hw09_billing_service_network:
    name: hw09_billing_service_network
    driver: bridge
  hw09_order_service_network:
    name: hw09_order_service_network
    driver: bridge
  hw09_notification_service_network:
    name: hw09_notification_service_network
    driver: bridge
  hw09_warehouse_service_network:
    name: hw09_warehouse_service_network
    driver: bridge
  hw09_delivery_service_network:
    name: hw09_delivery_service_network
    driver: bridge
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
