apiVersion: v1
kind: Secret
metadata:
  name: hw04-postgres-secret
  labels:
    app.kubernetes.io/name: hw04
    app.kubernetes.io/instance: hw04
type: Opaque
stringData:
  username: "hw04user"
  password: "hw04Password"
  SPRING_DATASOURCE_USERNAME: "hw04user"
  SPRING_DATASOURCE_PASSWORD: "hw04Password"
