CREATE TABLE IF NOT EXISTS notifications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT                                  NOT NULL DEFAULT 0,
    created             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    user_id             BIGINT                                  NOT NULL,
    message             VARCHAR(1024)                           NOT NULL,
    order_id            BIGINT                                  NOT NULL,
    notification_status VARCHAR(20)                             NOT NULL CHECK (notification_status IN
                                                                                     ('SUCCESS', 'CANCELED', 'FAILED')),
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id_order_id ON notifications (user_id, order_id);

DROP TRIGGER IF EXISTS trg_update_notifications_updated ON notifications;
CREATE OR REPLACE FUNCTION update_notifications_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_notifications_updated
    BEFORE UPDATE
    ON notifications
    FOR EACH ROW
EXECUTE FUNCTION update_notifications_updated();
