-- Read-модель контактов пользователя (USER -> NOTIFICATION, асинхронная репликация).
-- Данные приходят событием UserSyncEvent (user.sync.events / user.profile.sync).
-- UNIQUE по user_id гарантирует отношение 1:1 и идемпотентность upsert при повторной доставке.
-- Аудит-колонки (version/created/updated/created_by/last_modified_by) - общий базовый
-- класс AuditableEntity; updated_at хранит время события-источника (timestamp guard).
CREATE TABLE notification_contacts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    created          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    user_id          BIGINT       NOT NULL,
    email            VARCHAR(255) NOT NULL,
    phone            VARCHAR(20),
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification_contacts PRIMARY KEY (id),
    CONSTRAINT uk_notification_contacts_user_id UNIQUE (user_id)
);
