CREATE TABLE IF NOT EXISTS accounts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL DEFAULT 0,
    created          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),

    user_id          BIGINT                                  NOT NULL UNIQUE,
    balance          DECIMAL(19, 4)                          NOT NULL DEFAULT 0,
    enabled          BOOLEAN                                 NOT NULL DEFAULT TRUE,
    locked           BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);