replicaCount: 2

image:
  repository: akinxela/otusapp
  pullPolicy: IfNotPresent
  tag: hw06

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 8000
  protocol: TCP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
          backend:
            port: 80
  tls: []

ingress-nginx:
  enabled: true
  controller:
    ingressClassResource:
      enabled: true
      name: nginx
      default: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
        additionalLabels:
          release: monitoring
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8000
  failureThreshold: 30
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
  auth:
    database: "hw06db"
    username: "hw06user"
    password: ""
  primary:
    containerSecurityContext: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    persistence:
      size: 1Gi

flywayJob:
  enabled: true
  image:
    repository: flyway/flyway
    tag: "10.16.0"
  locations: "filesystem:/flyway/sql"
  schemas: "app"
  disableInApp: true

jwt:
  secretKey: ""