apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finalproject.fullname" . }}-app-secret
  labels:
    {{ include "finalproject.labels" . | nindent 4 }}
type: Opaque
stringData:
  INTERNAL_API_KEY: {{ .Values.secrets.internalApiKey | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  RABBIT_USERNAME: {{ .Values.rabbitmq.username | quote }}
  RABBIT_PASSWORD: {{ .Values.rabbitmq.password | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | quote }}
  RABBITMQ_DEFAULT_VHOST: "/"
