apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw04chart.fullname" . }}
  labels:
    {{ include "hw04chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{ include "hw04chart.selectorLabels" . | nindent 4 }}
