apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hw04chart.fullname" . }}-jwt-secret
  labels:
    {{ include "hw04chart.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.jwt.secretKey | b64enc | quote }}
