{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hw04chart.fullname" . }}-postgres-secret
  labels:
    {{ include "hw04chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
{{- end }}