-- Idempotency keys for POST /api/v1/order: one row per client-provided Idempotency-Key.
-- Replay semantics:
--   response_status/response_body are stored only on saga success (201 + order JSON);
--   on saga failure the key stays with the final saga_status, so a repeated request
--   never creates a second order and returns the current order state instead.
CREATE TABLE IF NOT EXISTS idempotency_keys
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL DEFAULT 0,
    created          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),

    idempotency_key  VARCHAR(64)                             NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    request_hash     VARCHAR(64)                             NOT NULL,
    order_id         BIGINT,
    response_status  INT,
    response_body    TEXT,
    saga_status      VARCHAR(30),
    expires_at       TIMESTAMP,

    CONSTRAINT pk_idempotency_keys PRIMARY KEY (id),
    CONSTRAINT uq_idempotency_keys_key UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_idempotency_keys_expires_at ON idempotency_keys (expires_at);

DROP TRIGGER IF EXISTS trg_update_idempotency_keys_updated ON idempotency_keys;
CREATE OR REPLACE FUNCTION update_idempotency_keys_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_idempotency_keys_updated
    BEFORE UPDATE
    ON idempotency_keys
    FOR EACH ROW
EXECUTE FUNCTION update_idempotency_keys_updated();
