-- Transactional Outbox для канала уведомлений ORDER -> NOTIFICATION.
-- Событие записывается в одной транзакции с финальным сохранением заказа,
-- затем scheduled-publisher вычитывает NEW и публикует в RabbitMQ.
-- UNIQUE по event_id исключает дубли записи в outbox; дедупликацию доставок
-- обеспечивает consumer (processed_messages).
CREATE TABLE IF NOT EXISTS notification_outbox
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   VARCHAR(36)                             NOT NULL,
    payload    TEXT                                    NOT NULL,
    status     VARCHAR(10)                             NOT NULL CHECK (status IN ('NEW', 'SENT', 'FAILED')),
    attempts   INT                                     NOT NULL DEFAULT 0,
    created_at TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at    TIMESTAMP,

    CONSTRAINT pk_notification_outbox PRIMARY KEY (id),
    CONSTRAINT uq_notification_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_status ON notification_outbox (status);
