CREATE TABLE IF NOT EXISTS transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL,
    created          TIMESTAMP                               NOT NULL,
    updated          TIMESTAMP                               NOT NULL,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),

    account_id       BIGINT                                  NOT NULL,
    transaction_type VARCHAR(255)                            NOT NULL CHECK (transaction_type IN ('DEPOSIT',
                                                                                                  'WITHDRAWAL',
                                                                                                  'REFUND')),
    amount           DECIMAL(19, 4),
    balance_before   DECIMAL(19, 4),
    balance_after    DECIMAL(19, 4),
    order_id         BIGINT,
    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT fk_transactions_account_id FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_order_id ON transactions (order_id);