CREATE TABLE IF NOT EXISTS courier_day_capacities
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT                                  NOT NULL DEFAULT 0,
    created             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    capacity_date       DATE                                    NOT NULL,
    courier_count       INTEGER                                 NOT NULL DEFAULT 0,

    CONSTRAINT pk_courier_day_capacities PRIMARY KEY (id),
    CONSTRAINT uq_courier_day_capacities_date UNIQUE (capacity_date),
    CONSTRAINT chk_courier_day_capacities_count CHECK (courier_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_courier_day_capacities_date ON courier_day_capacities (capacity_date);
