-- Read-модель адресов доставки пользователя (USER -> DELIVERY, асинхронная репликация).
-- Данные приходят событием UserSyncEvent (user.sync.events / user.profile.sync).
-- Natural key (user_id, source_address_id): идемпотентный upsert полного снимка;
-- source_address_id - id адреса в user_addresses USERService (source of truth).
-- Аудит-колонки (version/created/updated/created_by/last_modified_by) - общий базовый
-- класс AuditableEntity; updated_at хранит время события-источника (timestamp guard).
CREATE TABLE delivery_user_addresses
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT    NOT NULL DEFAULT 0,
    created           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(255),
    last_modified_by  VARCHAR(255),
    user_id           BIGINT    NOT NULL,
    source_address_id BIGINT    NOT NULL,
    full_address      TEXT      NOT NULL,
    city              VARCHAR(255),
    postal_code       VARCHAR(20),
    is_default        BOOLEAN   NOT NULL DEFAULT FALSE,
    preferences       TEXT,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_delivery_user_addresses PRIMARY KEY (id),
    CONSTRAINT uk_delivery_source_address UNIQUE (user_id, source_address_id)
);

CREATE INDEX idx_delivery_addresses_user_id ON delivery_user_addresses (user_id);
