CREATE TABLE IF NOT EXISTS courier_slots
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                 BIGINT                                  NOT NULL DEFAULT 0,
    created                 TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated                 TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(255),
    last_modified_by        VARCHAR(255),

    courier_day_capacity_id BIGINT                                  NOT NULL,
    slot_start              TIME                                    NOT NULL,
    slot_end                TIME                                    NOT NULL,

    CONSTRAINT pk_courier_slots PRIMARY KEY (id),
    CONSTRAINT fk_courier_slots_day_capacity
        FOREIGN KEY (courier_day_capacity_id) REFERENCES courier_day_capacities (id),
    CONSTRAINT uq_courier_slots_day_capacity_slot
        UNIQUE (courier_day_capacity_id, slot_start, slot_end),
    CONSTRAINT chk_courier_slots_time CHECK (slot_start < slot_end)
);

CREATE INDEX IF NOT EXISTS idx_courier_slots_day_capacity_id ON courier_slots (courier_day_capacity_id);
CREATE INDEX IF NOT EXISTS idx_courier_slots_start_end ON courier_slots (slot_start, slot_end);
