CREATE TABLE IF NOT EXISTS delivery_reservations
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                 BIGINT                                  NOT NULL DEFAULT 0,
    created                 TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated                 TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(255),
    last_modified_by        VARCHAR(255),

    order_id                BIGINT                                  NOT NULL,
    courier_slot_id         BIGINT                                  NOT NULL,
    assigned_courier_number INTEGER                                 NOT NULL,
    status                  VARCHAR(20)                             NOT NULL,

    CONSTRAINT pk_delivery_reservations PRIMARY KEY (id),
    CONSTRAINT fk_delivery_reservations_courier_slot
        FOREIGN KEY (courier_slot_id) REFERENCES courier_slots (id),
    CONSTRAINT uq_delivery_reservations_order_id UNIQUE (order_id),
    CONSTRAINT chk_delivery_reservations_courier_number CHECK (assigned_courier_number > 0),
    CONSTRAINT chk_delivery_reservations_status
        CHECK (status IN ('RESERVED', 'CONFIRMED', 'CANCELLED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_delivery_reservations_courier_slot_id ON delivery_reservations (courier_slot_id);
CREATE INDEX IF NOT EXISTS idx_delivery_reservations_status ON delivery_reservations (status);

-- Частичный уникальный индекс: защита от двойного бронирования номера курьера в слоте.
-- После CANCELLED/FAILED номер курьера освобождается и может быть использован повторно.
CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_reservations_active_slot_courier
    ON delivery_reservations (courier_slot_id, assigned_courier_number)
    WHERE status IN ('RESERVED', 'CONFIRMED');
