# yaml-language-server: $schema=https://json.schemastore.org/spring-configuration-metadata.json
spring:
  profiles:
    active: dev
  application:
    name: USERService
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}
  datasource:
    url: ${SPRING_DATASOURCE_URL_USER_SERVICE:jdbc:postgresql://localhost:5432/fpdb_user_service}
    username: ${SPRING_DATASOURCE_USERNAME_USER_SERVICE:fpuser_user_service}
    password: ${SPRING_DATASOURCE_PASSWORD_USER_SERVICE:fppass_user_service}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_ADDRESSES:localhost}
    port: 5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
  http:
    client:
      connect-timeout: ${HTTP_CLIENT_CONNECT_TIMEOUT:2s}
      read-timeout: ${HTTP_CLIENT_READ_TIMEOUT:3s}

server:
  port: ${SERVER_PORT_USER_SERVICE:8000}

management:
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,rabbitmq
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    ru.otus.hw: DEBUG

app:
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8006}
  billing-service-url: ${BILLING_SERVICE_URL:http://localhost:8001}
  security:
    jwt-secret-key: ${JWT_SECRET_KEY:}
    jwt-access-expiration-time: ${JWT_ACCESS_EXPIRATION:900000}
  internal-api-key: ${INTERNAL_API_KEY}
  rabbitmq:
    producer:
      exchange-name: users.events
      routing-key: user.created
    user-created:
      exchange-name: users.events
      queue-name: user.user-created.queue
      queue-type: classic
      routing-key: user.created
    user-sync:
      exchange-name: user.sync.events
      routing-key: user.profile.sync
    notification:
      exchange-name: notifications.events
      routing-key: notification.event
    consumer:
      exchange-name: accounts.events
      queue-name: user.account-activation.queue
      queue-type: classic
      routing-key: account.created
  outbox:
    publish-delay: ${OUTBOX_PUBLISH_DELAY:1000}
    cleanup-interval: ${OUTBOX_CLEANUP_INTERVAL:1h}
    retention: ${OUTBOX_RETENTION:7d}
  activation:
    timeout: ${BILLING_ACTIVATION_TIMEOUT:30m}
    check-interval-ms: ${ACTIVATION_CHECK_INTERVAL:300000}
