postgres:
  postgres-user:
    password: "hw07pass_user_service"
  postgres-billing:
    password: "hw07pass_billing_service"
  postgres-order:
    password: "hw07pass_order_service"
  postgres-notification:
    password: "hw07pass_notification_service"

secrets:
  internalApiKey: "mySecretKeyForInternalApiThatIsLongEnough2026HW07"
  jwtSecretKey: "mySecretKeyForJwtTokenGenerationThatIsLongEnough2026HW07"

rabbitmq:
  username: "guest"
  password: "guest"
