$ErrorActionPreference = 'Stop'

Write-Host '---> Minikube IP'
minikube ip
if ($LASTEXITCODE -ne 0) { throw 'minikube ip failed' }

Write-Host ''
Write-Host 'Add this line to C:\Windows\System32\drivers\etc\hosts (run editor as Administrator):'
Write-Host 'MINIKUBE_IP arch.homework'
Write-Host ''
Write-Host 'If ingress is not reachable, run in a separate elevated PowerShell window:'
Write-Host 'minikube tunnel'
Write-Host ''
Write-Host '============================================================'
Write-Host '  CRUD API endpoints (base URL: http://arch.homework)'
Write-Host '============================================================'
Write-Host ''
Write-Host '---> GET all users (paginated)'
Write-Host 'curl http://arch.homework/user'
Write-Host ''
Write-Host '---> GET user by ID'
Write-Host 'curl http://arch.homework/user/1'
Write-Host ''
Write-Host '---> GET users by IDs'
Write-Host 'curl "http://arch.homework/user?ids=1,2,3"'
Write-Host ''
Write-Host '---> POST create user'
Write-Host 'curl -X POST http://arch.homework/user -H "Content-Type: application/json" -d "{\"userName\":\"AlexNika\",\"firstName\":\"Alex\",\"lastName\":\"Nika\",\"email\":\"nikolaev-a@gmail.com\"}"'
Write-Host ''
Write-Host '---> PUT update user by ID'
Write-Host 'curl -X PUT http://arch.homework/user/1 -H "Content-Type: application/json" -d "{\"userName\":\"AlexNika\",\"firstName\":\"Alex\",\"lastName\":\"Nikolaev\",\"email\":\"alexander.nikolaev@gmail.com\"}"'
Write-Host ''
Write-Host '---> PATCH partially update user by ID'
Write-Host 'curl -X PATCH http://arch.homework/user/1 -H "Content-Type: application/json" -d "{\"lastName\":\"Nikolaev\"}"'
Write-Host ''
Write-Host '---> DELETE user by ID'
Write-Host 'curl -X DELETE http://arch.homework/user/1'
Write-Host ''
Write-Host '---> DELETE all users'
Write-Host 'curl -X DELETE http://arch.homework/user'
