CREATE TABLE IF NOT EXISTS product_stock
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT                                  NOT NULL DEFAULT 0,
    created             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    available_quantity  INTEGER                                 NOT NULL DEFAULT 0 CHECK (available_quantity >= 0),
    reserved_quantity   INTEGER                                 NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),

    CONSTRAINT pk_product_stock PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_reservations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT                                  NOT NULL DEFAULT 0,
    created             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    order_id            BIGINT                                  NOT NULL,
    product_id          BIGINT                                  NOT NULL,
    quantity            INTEGER                                 NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    status              VARCHAR(20)                             NOT NULL CHECK (status IN ('RESERVED',
                                                                                           'CONFIRMED',
                                                                                           'RELEASED',
                                                                                           'FAILED')),
    idempotency_key     BIGINT                                  NOT NULL UNIQUE,

    CONSTRAINT pk_product_reservations PRIMARY KEY (id),
    CONSTRAINT uq_product_reservations_order_product UNIQUE (order_id, product_id)
);


CREATE INDEX IF NOT EXISTS idx_product_reservation_order_id ON product_reservations (order_id);
CREATE INDEX IF NOT EXISTS idx_product_reservation_product_id ON product_reservations (product_id);

DROP TRIGGER IF EXISTS trg_update_product_stock_updated ON product_stock;
CREATE OR REPLACE FUNCTION update_product_stock_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_product_stock_updated
    BEFORE UPDATE
    ON product_stock
    FOR EACH ROW
EXECUTE FUNCTION update_product_stock_updated();

DROP TRIGGER IF EXISTS trg_update_product_reservations_updated ON product_reservations;
CREATE OR REPLACE FUNCTION update_product_reservations_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_product_reservations_updated
    BEFORE UPDATE
    ON product_reservations
    FOR EACH ROW
EXECUTE FUNCTION update_product_reservations_updated();