CREATE TABLE IF NOT EXISTS products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT                                  NOT NULL DEFAULT 0,
    created             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated             TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(1024),
    price               DECIMAL(19, 4)                          NOT NULL DEFAULT 0,
    product_stock_id    BIGINT                                  UNIQUE,

    CONSTRAINT pk_products PRIMARY KEY (id)
);

DROP TRIGGER IF EXISTS trg_update_products_updated ON products;
CREATE OR REPLACE FUNCTION update_products_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_products_updated
    BEFORE UPDATE
    ON products
    FOR EACH ROW
EXECUTE FUNCTION update_products_updated();

ALTER TABLE products
    ADD CONSTRAINT fk_product_product_stock
        FOREIGN KEY (product_stock_id) REFERENCES product_stock(id);

ALTER TABLE product_reservations
    ADD CONSTRAINT fk_product_reservation_product
        FOREIGN KEY (product_id) REFERENCES products(id);
