SET search_path TO app;

CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT       NOT NULL,
    created          TIMESTAMP    NOT NULL,
    updated          TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    username         VARCHAR(255) NOT NULL,
    firstname        VARCHAR(255),
    lastname         VARCHAR(255),
    email            VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_EMAIL UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_USERNAME UNIQUE (username);

CREATE INDEX idx_users_username_email ON users (username, email);