apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hw08chart.fullname" . }}-postgres-secret
  labels:
    {{ include "hw08chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $pg := .Values.postgres }}
  {{ $pg.passwordSecretKey }}: {{ $pg.password | quote }}
  {{- end }}
