CREATE TABLE IF NOT EXISTS orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL DEFAULT 0,
    created          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),

    user_id          BIGINT                                  NOT NULL,
    price            DECIMAL(19, 4)                          NOT NULL DEFAULT 0 CHECK (price >= 0),
    description      VARCHAR(255),
    order_status     VARCHAR(20)                             NOT NULL CHECK (order_status IN
                                                                             ('PENDING', 'PROCESSING', 'PLACED',
                                                                              'CANCELED', 'FAILED')),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders (user_id, order_status);

DROP TRIGGER IF EXISTS trg_update_orders_updated ON orders;
CREATE OR REPLACE FUNCTION update_orders_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_orders_updated
    BEFORE UPDATE
    ON orders
    FOR EACH ROW
EXECUTE FUNCTION update_orders_updated();