CREATE TABLE IF NOT EXISTS order_saga_state
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL DEFAULT 0,
    created          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated          TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),

    order_id         BIGINT                                  NOT NULL,
    saga_status      VARCHAR(30)                             NOT NULL,
    failure_step     VARCHAR(30),
    failure_reason   VARCHAR(2048),

    CONSTRAINT pk_order_saga_state PRIMARY KEY (id),
    CONSTRAINT uq_order_saga_state_order_id UNIQUE (order_id),
    CONSTRAINT fk_order_saga_state_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX IF NOT EXISTS idx_order_saga_state_saga_status ON order_saga_state (saga_status);

DROP TRIGGER IF EXISTS trg_update_order_saga_state_updated ON order_saga_state;
CREATE OR REPLACE FUNCTION update_order_saga_state_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_order_saga_state_updated
    BEFORE UPDATE
    ON order_saga_state
    FOR EACH ROW
EXECUTE FUNCTION update_order_saga_state_updated();
