CREATE TABLE user_profile
(
    id               BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    version          BIGINT       NOT NULL,
    created          TIMESTAMP    NOT NULL,
    updated          TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    username         VARCHAR(255) NOT NULL,
    firstname        VARCHAR(255),
    lastname         VARCHAR(255),
    birthdate        TIMESTAMP,
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

ALTER TABLE users
    ADD COLUMN profile_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT fk_user_profile
        FOREIGN KEY (profile_id)
            REFERENCES user_profile (id)
            ON DELETE SET NULL;

DO $$
    DECLARE
        max_user_id BIGINT;
    BEGIN
        SELECT COALESCE(MAX(id), 0) INTO max_user_id FROM users;
        PERFORM setval(pg_get_serial_sequence('user_profile', 'id'), max_user_id + 10);
    END $$;