-- Статус биллинг-аккаунта пользователя (USER -> BILLING событийная хореография):
-- PENDING - пользователь создан, биллинг-аккаунт ещё создаётся асинхронно;
-- ACTIVE  - аккаунт создан, полная функциональность;
-- BLOCKED - аккаунт не создан за тайм-аут (логин запрещён через locked=true).
-- Существующие пользователи уже имеют аккаунты (старый синхронный путь) - дефолт ACTIVE;
-- новые пользователи получают PENDING из кода.
ALTER TABLE users
    ADD COLUMN account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

COMMENT ON COLUMN users.account_status IS
    'Billing account lifecycle status: PENDING / ACTIVE / BLOCKED';

-- Transactional Outbox для события UserCreatedEvent (USER -> BILLING).
-- Событие записывается в одной транзакции с сохранением пользователя,
-- затем scheduled-publisher вычитывает NEW и публикует в RabbitMQ (users.events / user.created).
-- UNIQUE по event_id исключает дубли записи в outbox; идемпотентность потребления -
-- по natural key userId (unique accounts.user_id).
CREATE TABLE IF NOT EXISTS user_outbox
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   VARCHAR(36)                             NOT NULL,
    payload    TEXT                                    NOT NULL,
    status     VARCHAR(10)                             NOT NULL CHECK (status IN ('NEW', 'SENT', 'FAILED')),
    attempts   INT                                     NOT NULL DEFAULT 0,
    created_at TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at    TIMESTAMP,

    CONSTRAINT pk_user_outbox PRIMARY KEY (id),
    CONSTRAINT uq_user_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_user_outbox_status ON user_outbox (status);
