-- Асинхронная репликация контактных данных пользователя (USER -> NOTIFICATION, DELIVERY).
-- USERService остаётся source of truth; потребители обновляют локальные read-модели по событию.

-- phone: строго один, nullable (несколько NULL допустимы для UNIQUE в PostgreSQL).
ALTER TABLE user_profile ADD COLUMN phone VARCHAR(20);
ALTER TABLE user_profile ADD CONSTRAINT uk_user_profile_phone UNIQUE (phone);

-- Адреса доставки пользователя (1:N). Source of truth - USERService; снимок адресов
-- публикуется в событии UserSyncEvent, DELIVERYService ведёт свою read-модель по
-- natural key (user_id, source_address_id).
-- Аудит-колонки (version/created/updated/created_by/last_modified_by) - общий базовый
-- класс AuditableEntity, как у остальных доменных сущностей.
CREATE TABLE user_addresses (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version              BIGINT NOT NULL DEFAULT 0,
    created              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(255),
    last_modified_by     VARCHAR(255),
    user_id              BIGINT NOT NULL,
    full_address         TEXT NOT NULL,
    city                 VARCHAR(255),
    postal_code          VARCHAR(20),
    is_default           BOOLEAN NOT NULL DEFAULT FALSE,
    delivery_preferences TEXT,
    CONSTRAINT pk_user_addresses PRIMARY KEY (id),
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_addresses_user_id ON user_addresses (user_id);

-- Общий outbox теперь несёт события двух типов:
--   USER_CREATED - USER -> BILLING (users.events / user.created);
--   USER_SYNC    - USER -> NOTIFICATION, DELIVERY (user.sync.events / user.profile.sync).
-- Дефолт USER_CREATED совместим с уже записанными строками.
ALTER TABLE user_outbox ADD COLUMN event_type VARCHAR(20) NOT NULL DEFAULT 'USER_CREATED';
ALTER TABLE user_outbox ADD CONSTRAINT chk_user_outbox_event_type
    CHECK (event_type IN ('USER_CREATED', 'USER_SYNC'));
