CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT       NOT NULL,
    created          TIMESTAMP    NOT NULL,
    updated          TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    email            VARCHAR(255) NOT NULL UNIQUE,
    password         VARCHAR(255) NOT NULL,
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    locked           BOOLEAN      NOT NULL DEFAULT FALSE,
    account_expired  BOOLEAN      NOT NULL DEFAULT FALSE,
    credentials_expired BOOLEAN    NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_EMAIL UNIQUE (email);

CREATE INDEX idx_users_email_enabled ON users (email, enabled);