$ErrorActionPreference = 'Stop'

Write-Host '---> Minikube IP'
minikube ip
if ($LASTEXITCODE -ne 0) { throw 'minikube ip failed' }

Write-Host ''
Write-Host 'Add this line to C:\Windows\System32\drivers\etc\hosts (run editor as Administrator):'
Write-Host 'MINIKUBE_IP arch.homework'
Write-Host ''
Write-Host 'If ingress is not reachable, run in a separate elevated PowerShell window:'
Write-Host 'minikube tunnel'
Write-Host ''
Write-Host '============================================================'
Write-Host '  API endpoints (base URL: http://arch.homework)'
Write-Host '============================================================'
Write-Host ''
Write-Host '---> Health checks'
Write-Host 'curl http://arch.homework/health/user'
Write-Host 'curl http://arch.homework/health/billing'
Write-Host 'curl http://arch.homework/health/order'
Write-Host 'curl http://arch.homework/health/notification'
Write-Host ''
Write-Host '---> Auth'
Write-Host 'curl -X POST http://arch.homework/api/v1/auth/register -H "Content-Type: application/json" -d "{\"userName\":\"testuser\",\"firstName\":\"Test\",\"lastName\":\"User\",\"email\":\"test@example.com\",\"password\":\"password123\"}"'
Write-Host ''
Write-Host '---> Billing'
Write-Host 'curl http://arch.homework/api/v1/account/user/{userId}'
Write-Host 'curl -X POST http://arch.homework/api/v1/account/{userId}/deposit -H "Content-Type: application/json" -d "{\"amount\":1000}"'
Write-Host ''
Write-Host '---> Order'
Write-Host 'curl -X POST http://arch.homework/api/v1/order -H "Content-Type: application/json" -d "{\"userId\":1,\"amount\":250,\"description\":\"Test order\"}"'
Write-Host ''
Write-Host '---> Notification'
Write-Host 'curl "http://arch.homework/api/v1/notification?userId={userId}"'
