apiVersion: v2
name: finalproject
description: OTUS Final Project Microservices (User, Billing, Order, Notification, Warehouse, Delivery) + idempotency
type: application
version: 0.2.0
appVersion: "0.1.0"
