{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw07chart.fullname" $ }}-{{ $name }}
  labels:
    {{ include "hw07chart.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}
