apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw07chart.fullname" . }}-rabbitmq
  labels:
    {{ include "hw07chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          envFrom:
            - secretRef:
                name: {{ include "hw07chart.fullname" . }}-app-secret
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw07chart.fullname" . }}-rabbitmq
  labels:
    {{ include "hw07chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
