CREATE TABLE roles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT       NOT NULL,
    created          TIMESTAMP    NOT NULL,
    updated          TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    name             VARCHAR(50)  NOT NULL UNIQUE,
    description      VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE INDEX idx_roles_name ON roles (name);
